# German translations for vigilo-vigiconf.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 13:19+0100\n"
"PO-Revision-Date: 2011-01-15 09:11+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:74
#, python-format
msgid "ERROR: %s"
msgstr "FEHLER: %s"

#: src/vigilo/vigiconf/commandline.py:77
msgid "No server to manage."
msgstr "Kein Server zur Verwaltung."

#: src/vigilo/vigiconf/commandline.py:139
msgid ""
"Vigilo server management is only available in the Enterprise edition. "
"Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:159
msgid "usage: "
msgstr "Verwendung: "

#: src/vigilo/vigiconf/commandline.py:160
#, python-format
msgid "conflicting option string(s): %s"
msgstr "widersprüchliche Option String(s): %s"

#: src/vigilo/vigiconf/commandline.py:161
msgid "subcommands"
msgstr "Unterbefehle"

#: src/vigilo/vigiconf/commandline.py:162
#, python-format
msgid "unrecognized arguments: %s"
msgstr "Unbekannte Argumente: %s"

#: src/vigilo/vigiconf/commandline.py:163
msgid "expected one argument"
msgstr "ein Argument erwartet"

#: src/vigilo/vigiconf/commandline.py:164
msgid "expected at most one argument"
msgstr "höchstens ein Argument erwartet"

#: src/vigilo/vigiconf/commandline.py:165
msgid "expected at least one argument"
msgstr "mindestens ein Argument erwartet"

#: src/vigilo/vigiconf/commandline.py:166
#, python-format
msgid "expected %s argument(s)"
msgstr "%s Argument(e) erwartet"

#: src/vigilo/vigiconf/commandline.py:167
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr "ungültige Auswahl: %r (gewählt aus %s)"

#: src/vigilo/vigiconf/commandline.py:168
msgid "positional arguments"
msgstr "positionale Argumente"

#: src/vigilo/vigiconf/commandline.py:169
msgid "optional arguments"
msgstr "optionale Argumente"

#: src/vigilo/vigiconf/commandline.py:170
msgid "too few arguments"
msgstr "zu wenig Argumente"

#: src/vigilo/vigiconf/commandline.py:171
#, python-format
msgid "argument %s is required"
msgstr "Argument %s erforderlich"

#: src/vigilo/vigiconf/commandline.py:172
#, python-format
msgid "one of the arguments %s is required"
msgstr "eines der Argumente %s ist erforderlich"

#: src/vigilo/vigiconf/commandline.py:173
#, python-format
msgid "%s: error: %s\n"
msgstr "%s: Fehler: %s\n"

#: src/vigilo/vigiconf/commandline.py:174
msgid "show this help message and exit"
msgstr "Diese Hilfemeldung anzeigen und beenden"

#: src/vigilo/vigiconf/commandline.py:175
msgid "show program's version number and exit"
msgstr "Versionsnummer des Programms anzeigen und beenden"

#: src/vigilo/vigiconf/commandline.py:179
msgid "Debug mode."
msgstr "Debug-Modus."

#: src/vigilo/vigiconf/commandline.py:181
msgid "Don't try to switch to the correct user."
msgstr "Nicht versuchen, zum korrekten Benutzer zu wechseln."

#: src/vigilo/vigiconf/commandline.py:186
msgid "Vigilo configuration manager"
msgstr "Vigilo Konfigurationsmanager"

#: src/vigilo/vigiconf/commandline.py:187
msgid "Subcommands"
msgstr "Unterbefehle"

#: src/vigilo/vigiconf/commandline.py:193
msgid "Prints a summary of the current configuration."
msgstr "Druckt eine Übersicht der aktuellen Konfiguration."

#: src/vigilo/vigiconf/commandline.py:196
msgid "Supervision servers to query, all of them if not specified."
msgstr "Abzufragender Kontrollserver, alle, wenn nicht angegeben."

#: src/vigilo/vigiconf/commandline.py:203
msgid "Application status management."
msgstr "Anwendungsstatus-Management."

#: src/vigilo/vigiconf/commandline.py:207
msgid "Stop the applications."
msgstr "Anwendungen beenden."

#: src/vigilo/vigiconf/commandline.py:209
msgid "Start the applications."
msgstr "Anwendungen starten."

#: src/vigilo/vigiconf/commandline.py:211
msgid "Restart the applications."
msgstr "Anwendungen erneut starten."

#: src/vigilo/vigiconf/commandline.py:213
msgid "Applications to manage, all of them if not specified."
msgstr "Zu verwaltende Anwendungen, alle, wenn nicht  angegeben."

#: src/vigilo/vigiconf/commandline.py:235
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""
"Stellt die Konfiguration auf jedem Server bereit, wenn sich die "
"Konfiguration geändert hat."

#: src/vigilo/vigiconf/commandline.py:239
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""
"Den Prozess nach Dateierstellung beenden, bevor die Datein verschoben "
"werden."

#: src/vigilo/vigiconf/commandline.py:242
msgid ""
"Stop after pushing the files to the remote servers, and before restarting"
" the services."
msgstr ""
"Nach Verschieben der Datein zum Remoteserver und vor erneutem Start von "
"Services beenden."

#: src/vigilo/vigiconf/commandline.py:245
msgid "Deploy the given revision"
msgstr "Gegebene Revision bereitstellen"

#: src/vigilo/vigiconf/commandline.py:247
msgid ""
"Force the immediate execution of the command. Do not wait. Bypass all "
"checks."
msgstr ""
"Sofortige Ausführung des Befehls erzwingen. Nicht warten. Alle Prüfungen "
"umgehen."

#: src/vigilo/vigiconf/commandline.py:250
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""
"Nur Simulation, es wird keine Kopie wirklich erstellt, kein Commit in der"
" Datenbank."

#: src/vigilo/vigiconf/commandline.py:253
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr "Kontrollserver zur Bereitstellung, alle, wenn nicht angegeben."

#: src/vigilo/vigiconf/commandline.py:260
msgid "Discover the services available on a remote server."
msgstr "Services eines Remoteserver entdecken ."

#: src/vigilo/vigiconf/commandline.py:265
msgid "Output file. Default: standard output."
msgstr "Ausgabedatei. Standardmäßig: Standardausgabe."

#: src/vigilo/vigiconf/commandline.py:267
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr "SNMP Community. Fehler: %(default)s."

#: src/vigilo/vigiconf/commandline.py:269
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr "SNMP Version. Fehler: %(default)s."

#: src/vigilo/vigiconf/commandline.py:271
#, python-format
msgid "Main group. Default: %(default)s."
msgstr "Hauptgruppe. Fehler: %(default)s."

#: src/vigilo/vigiconf/commandline.py:273
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk "
"command on the '.1' OID with the '-OnQe' options."
msgstr ""
"Zu scannende Hosts oder Datein. Die Datein müssen das Ergebnis eines "
"snmpwalk Befehls auf '.1' OID mit den  '-OnQe' Optionen sein."

#: src/vigilo/vigiconf/commandline.py:281
msgid "Enables or disables a Vigilo server"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:284
msgid "Don't re-deploy the configuration, only set the status."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:287
msgid "New status"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:289
msgid "Server name(s) to enable/disable"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:300
msgid ""
"VigiConf was launched as user 'root'. Switching to user 'vigiconf' "
"instead."
msgstr ""
"VigiConf wurde als Benutzer 'root' gestartet. Stattdessen zu Benutzer "
"'vigiconf' wechseln."

#: src/vigilo/vigiconf/commandline.py:305
msgid "Unable to switch to user 'vigiconf'. Aborting."
msgstr "Es kann nicht zu Benutzer 'vigiconf' gewechselt werden. Wird abgebrochen."

#: src/vigilo/vigiconf/commandline.py:329
msgid "VigiConf was not launched as user 'vigiconf'. Aborting."
msgstr "VigiConf wurde nicht als Benutzer 'vigiconf' gestartet. Wird abgebrochen."

#: src/vigilo/vigiconf/commandline.py:362
#, python-format
msgid ""
"Can't obtain lock on lockfile (%(lockfile)s). VigiConf already running ? "
"REASON : %(error)s"
msgstr ""
"Keine Sperre bei dieser Lock-Datei (%(lockfile)s) möglich. Wurde VigiConf"
" schon gestartet ? URSACHE: %(error)s"

#: src/vigilo/vigiconf/commandline.py:375
#: src/vigilo/vigiconf/commandline.py:377
#, python-format
msgid "VigiConf error: %s"
msgstr "VigiConf Fehler: %s"

#: src/vigilo/vigiconf/conf.py:299
msgid "Error loading configuration"
msgstr "Fehler beim Laden der Konfiguration"

#: src/vigilo/vigiconf/discoverator.py:78
#, python-format
msgid "%s: No such file"
msgstr "%s: Datei nicht vorhanden"

#: src/vigilo/vigiconf/discoverator.py:90
#, python-format
msgid ""
"Invalid HOSTNAME detected in SNMPv2-MIB::sysName.0: \"%s\" (blank "
"character not allowed)"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:125
msgid "The \"snmpwalk\" command is not installed."
msgstr "Der \"snmpwalk\"-Befehl ist nicht installiert."

#: src/vigilo/vigiconf/discoverator.py:128
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)s"
msgstr ""
"Fehlschlagen des SNMP Laufbefehls mit Status %(status)s und Meldung:\n"
"\"\n"
"\"%(msg)s\n"
"\"\n"
"\"Befehl war: %(cmd)s"

#: src/vigilo/vigiconf/applications/nagios_hls/generator.py:71
msgid "No server has been configured to host High-Level Services"
msgstr "Es wurde kein Server konfiguriert, um High-Level Services zu beherbergen"

#: src/vigilo/vigiconf/applications/vigirrd/generator.py:79
#, python-format
msgid "All the defined DSes are not graphed: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:223
#, python-format
msgid "Can't find the validation script for app %(app)s: %(error)s"
msgstr ""
"Gültigkeitsprüfungsskript für app %(app)s kann nicht gefunden werden: "
"%(error)s"

#: src/vigilo/vigiconf/lib/application.py:261
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr ""
"%(app)s: Gültigkeitsprüfung für Server '%(server)s' fehlgeschlagen: "
"%(reason)s"

#: src/vigilo/vigiconf/lib/application.py:268
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr "%(app)s : Gültigkeitsprüfung für Server erfolgreich: %(server)s"

#: src/vigilo/vigiconf/lib/application.py:312
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr ""
"%(app)s : Qualifikation bei '%(server)s' fehlgeschlagen - URSACHE: "
"%(reason)s"

#: src/vigilo/vigiconf/lib/application.py:320
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr "%(app)s : Qualifikation bei Server erfolgreich: %(server)s"

#: src/vigilo/vigiconf/lib/application.py:363
#: src/vigilo/vigiconf/lib/application.py:387
#, python-format
msgid "%s : Start process failed."
msgstr "%s : Starten des Prozesses fehlgeschlagen."

#: src/vigilo/vigiconf/lib/application.py:399
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr "%(app)s wird auf %(server)s gestartet..."

#: src/vigilo/vigiconf/lib/application.py:408
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr "%(app)s auf %(server)s kann nicht gestartet werden - URSACHE %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:416
#, python-format
msgid "%(app)s started on %(server)s"
msgstr "%(app)s auf %(server)s gestartet"

#: src/vigilo/vigiconf/lib/application.py:456
#: src/vigilo/vigiconf/lib/application.py:480
#, python-format
msgid "%s : Stop process failed."
msgstr "%s : Beenden des Prozesses fehlgeschlagen."

#: src/vigilo/vigiconf/lib/application.py:492
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr "%(app)s auf %(server)s werden beendet ..."

#: src/vigilo/vigiconf/lib/application.py:501
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr "%(app)s auf %(server)s kann nicht beendet werden - URSACHE %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:509
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr "%(app)s auf %(server)s beendet"

#: src/vigilo/vigiconf/lib/dispatchator.py:173
#, python-format
msgid ""
"Incoherent configuration: application %(app)s has an entry point named "
"%(epname)s in package %(eppkg)s"
msgstr ""
"Inkohärente Konfiguration: Anwendung %(app)s hat einen Einstiegspunkt "
"namens %(epname)s im Paket %(eppkg)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:178
#, python-format
msgid "Application %s is installed but disabled (see conf.d/general/apps.py)"
msgstr ""
"Anwendung %s ist installiert, jedoch deaktiviert (siehe "
"conf.d/general/apps.py)"

#: src/vigilo/vigiconf/lib/dispatchator.py:182
#, python-format
msgid "Application %s is not unique."
msgstr "Anwendung %s ist nicht eindeutig."

#: src/vigilo/vigiconf/lib/dispatchator.py:183
#, python-format
msgid " Providing modules: %s"
msgstr " Module: %s werden bereitgestellt"

#: src/vigilo/vigiconf/lib/dispatchator.py:192
#, python-format
msgid ""
"Application %s has been added to conf.d/general/apps.py, but is not "
"installed"
msgstr ""
"Anwendung %s wurde zu conf.d/general/apps.py hinzugefügt, ist jedoch "
"nicht installiert"

#: src/vigilo/vigiconf/lib/dispatchator.py:236
msgid "Generation failed!"
msgstr "Generierung fehlgeschlagen!"

#: src/vigilo/vigiconf/lib/dispatchator.py:239
msgid "Generation successful"
msgstr "Generierung erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:244
msgid "Validation Successful"
msgstr "Gültigkeitsprüfung erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:249
msgid "Commit Successful"
msgstr "Commit erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:258
msgid ""
"You can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""
"Sie können nicht zu einer früheren Revision zurückkehren, wenn Sie Ihre "
"Konfiguration geändert haben. 'svn revert' verwenden, um Änderungen "
"rückgängig zu machen"

#: src/vigilo/vigiconf/lib/dispatchator.py:272
#, python-format
msgid "Can't get the SVN status for the configuration dir: %s"
msgstr "Der SVN Status für die Konfiguration dir: %s kann nicht erhalten werden"

#: src/vigilo/vigiconf/lib/dispatchator.py:290
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""
"Kann nicht aktualisiert werden, da der Konfigurationsparameter "
"'svnrepository' leer ist"

#: src/vigilo/vigiconf/lib/dispatchator.py:311
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr "%(path)s kann dem Repository nicht hinzugefügt werden: %(error)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:329
#, python-format
msgid "Can't remove %(path)s from repository: %(error)s"
msgstr "%(path)s kann nicht aus dem Repository entfernt werden: %(error)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:337
msgid ""
"Not committing because the 'svnrepository' configuration parameter is "
"empty"
msgstr ""
"Commit wird nicht ausgeführt, das der Konfigurationsparameter "
"'svnrepository' leer ist"

#: src/vigilo/vigiconf/lib/dispatchator.py:349
#, python-format
msgid "Can't commit the configuration dir in SVN: %s"
msgstr "Commit kann für die Konfiguration dir in SVN nicht ausgeführt werden: %s"

#: src/vigilo/vigiconf/lib/dispatchator.py:364
#, python-format
msgid ""
"Can't execute the request to update the local copy. COMMAND %(cmd)s "
"FAILED. REASON: %(reason)s"
msgstr ""
"Die Anforderung der Aktualisierung der lokalen Kopie kann nicht "
"ausgeführt werden. BEFEHL %(cmd)s FEHLGESCHLAGEN. URSACHE: %(reason)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:406
#, python-format
msgid "Can't execute the request to get the current revision: %s"
msgstr ""
"Die Anforderung die aktuelle Revision: %szu erhalten kann nicht "
"ausgeführt werden"

#: src/vigilo/vigiconf/lib/dispatchator.py:478
msgid ""
"The configurations files have not been transfered on every server. See "
"above for more information."
msgstr ""
"Die Konfigurationsdatein wurden nicht auf alle Server übertragen. Weitere"
" Informationen siehe oben."

#: src/vigilo/vigiconf/lib/dispatchator.py:530
msgid "All servers are up-to-date, no deployment needed."
msgstr "Alle Server sind aktualisiert. Kein Bereitstellung erforderlich."

#: src/vigilo/vigiconf/lib/dispatchator.py:642
msgid "Switch directories was not successful on each server."
msgstr "Wechseln der Verzeichnisse war nicht auf jedem Server erfolgreich."

#: src/vigilo/vigiconf/lib/dispatchator.py:669
msgid "All servers are up-to-date. No restart needed."
msgstr "Alle Server sind aktualisiert. Kein Neustart erforderlich."

#: src/vigilo/vigiconf/lib/dispatchator.py:689
msgid "Stop applications failed"
msgstr "Beenden der Anwendungen fehlgeschlagen"

#: src/vigilo/vigiconf/lib/dispatchator.py:706
msgid "Start applications failed"
msgstr "Starten der Anwendungen fehlgeschlagen"

#: src/vigilo/vigiconf/lib/dispatchator.py:711
#, python-format
msgid "Current revision in the repository : %d"
msgstr "Aktuelle Revision im Repository : %d"

#: src/vigilo/vigiconf/lib/dispatchator.py:719
msgid "(should be deployed)"
msgstr "(sollte bereitgestellt werden)"

#: src/vigilo/vigiconf/lib/dispatchator.py:721
msgid "(should restart)"
msgstr "(sollte neustarten)"

#: src/vigilo/vigiconf/lib/dispatchator.py:722
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr "Revisionen für Server %(server)s : %(rev)s%(dep)s%(restart)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:728
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""
"Für den Server: %(server)s kann keine Revision erhalten werden. URSACHE :"
" %(reason)s"

#: src/vigilo/vigiconf/lib/remotecommand.py:117
msgid "Server name set to None."
msgstr "Servername auf Keiner gesetzt."

#: src/vigilo/vigiconf/lib/remotecommand.py:119
msgid "Server name incorrect (length = 0)."
msgstr "Servername ungültig  (Länge = 0)."

#: src/vigilo/vigiconf/lib/remotecommand.py:179
msgid "Unknown command type."
msgstr "Unbekannter Befehlstyp."

#: src/vigilo/vigiconf/lib/remotecommand.py:196
#, python-format
msgid "The source file does not exist: %s"
msgstr "Die Quelldatei ist nicht vorhanden: %s"

#: src/vigilo/vigiconf/lib/remotecommand.py:213
#: src/vigilo/vigiconf/lib/remotecommand.py:246
msgid "Cannot reach server."
msgstr "Server kann nicht erreicht werden."

#: src/vigilo/vigiconf/lib/remotecommand.py:216
#: src/vigilo/vigiconf/lib/remotecommand.py:248
msgid "Cannot find file."
msgstr "Datei kann nicht gefunden werden."

#: src/vigilo/vigiconf/lib/revisionmanager.py:169
#, python-format
msgid "Cannot write the revision file: %s"
msgstr "Revisionsdatei: %s kann nicht beschrieben werden"

#: src/vigilo/vigiconf/lib/server.py:83
msgid "On the Community Edition, you can only use localhost"
msgstr "Auf der Community Ausgabe, kann nur der Lokalhost benutzt werden"

#: src/vigilo/vigiconf/lib/server.py:178
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""
"Die Konfiguration auf %(server)s kann nicht aktiviert werden. BEFEHL "
"%(cmd)s FEHLGESCHLAGEN. URSACHE: %(reason)s"

#: src/vigilo/vigiconf/lib/server.py:204
#, python-format
msgid "Can't tar config for server %(server)s: %(error)s"
msgstr "Konfig kann für Server %(server)s nicht archiviert werden: %(error)s"

#: src/vigilo/vigiconf/lib/server.py:222
#, python-format
msgid "%s : deployement successful."
msgstr "%s : erfolgreich bereitgestellt."

#: src/vigilo/vigiconf/lib/server.py:236
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr "Datein (%(from)s können nicht in %(to)s) kopiert werden: %(error)s."

#: src/vigilo/vigiconf/lib/systemcommand.py:108
#, python-format
msgid "Command %(cmd)s failed with code %(code)s and message: %(msg)s"
msgstr "Befehl %(cmd)s fehlgeschlagen mit Code %(code)s und Meldung: %(msg)s"

#: src/vigilo/vigiconf/lib/validator.py:123
msgid "No server configuration to be generated"
msgstr "Keine zu erstellende Serverkonfiguration"

#: src/vigilo/vigiconf/lib/validator.py:127
msgid "No application configuration to be generated"
msgstr "Keine zu erstellende Anwendungskonfiguration"

#: src/vigilo/vigiconf/lib/validator.py:131
msgid "No host configuration to be generated"
msgstr "Keine zu erstellende Hostkonfiguration"

#: src/vigilo/vigiconf/lib/validator.py:141
#, python-format
msgid ""
"The number of host entries in the database does not match the number of "
"hosts in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:169
#, python-format
msgid ""
"The number of services entries in the database does not match the number "
"of services in the configuration. Database: %(db)d, configuration: "
"%(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:183
#, python-format
msgid ""
"The number of apps entries in the database does not match the number of "
"apps in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:200
#, python-format
msgid ""
"The number of ventilation entries in the database does not match the "
"number of host and apps. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:227
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""
"%(nb_gens)d Generatoren sind vorhanden und %(nb_apps)d Anwendungen sind "
"konfiguriert worden"

#: src/vigilo/vigiconf/lib/validator.py:234
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr "########> Fehler in %(source)s (object %(object)s): %(error)s"

#: src/vigilo/vigiconf/lib/validator.py:241
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr "====> Warnung in %(source)s (object %(object)s): %(error)s"

#: src/vigilo/vigiconf/lib/validator.py:247
#, python-format
msgid "%d errors"
msgstr "%d Fehler"

#: src/vigilo/vigiconf/lib/validator.py:248
#, python-format
msgid "%d warnings"
msgstr "%d Warnungen"

#: src/vigilo/vigiconf/lib/validator.py:250
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""
"%(nbGenerators)d Generatoren haben %(nbHosts)d Hosts auf %(nbServers)d "
"Servern konfiguriert."

#: src/vigilo/vigiconf/lib/validator.py:252
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr "%(filesWritten)d Datein wurden in %(dirsCreated)d Verzeichnissen erstellt"

#: src/vigilo/vigiconf/lib/confclasses/host.py:168
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""
"Test \"%(test_name)s\" auf \"%(host)s\" benötigt die folgenden Argumente:"
" %(args)s (and only those)"

#: src/vigilo/vigiconf/lib/confclasses/host.py:739
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:258
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:115
#, python-format
msgid "Not enough memory to validate %(file)s using schema %(schema)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:746
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:265
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:122
#, python-format
msgid "Invalid XML validation schema %(schema)s found while validating %(file)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:753
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:272
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:129
#, python-format
msgid "XML validation failed (%(file)s with schema %(schema)s)"
msgstr "XML Gültigkeitsprüfung (%(file)s mit Schema %(schema)s) fehlgeschlagen"

#: src/vigilo/vigiconf/lib/confclasses/host.py:758
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:277
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:134
#, python-format
msgid ""
"XML validation failed for file %(file)s, using schema %(schema)s, due to "
"an error. Make sure the permissions are set correctly."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:806
#, python-format
msgid "Invalid ventilation group: %s"
msgstr "Ungültige Aufteilungsgruppe: %s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:840
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr "Ungültiger Gewichtungswert für Test %(test)s auf Host %(host)s: %(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/host.py:885
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:108
#: src/vigilo/vigiconf/loaders/hlservice.py:143
#, python-format
msgid "Invalid group name (%s)"
msgstr "Ungültiger Gruppenname (%s)"

#: src/vigilo/vigiconf/lib/confclasses/host.py:894
#, python-format
msgid "Invalid weight value for host %(host)s: %(weight)r"
msgstr "Ungültiger Gewichtungswert für Host %(host)s: %(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/host.py:907
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr "Host \"%s\" muss mindestens einer Gruppe zugeordnet werden."

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:356
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""
"Ungültiger Gewichtungswert für Test %(test)s in Vorlage %(tpl)s: "
"%(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:378
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr "Ungültiger Gewichtungswert für Vorlage %(tpl)s: %(weight)r"

#: src/vigilo/vigiconf/lib/dispatchmodes/__init__.py:54
msgid ""
"You are trying remote deployment on the Community edition. This feature "
"is only available in the Enterprise edition. Aborting."
msgstr ""
"Sie versuchen eine Remote-Bereitstellung bei der Community Ausgabe. Diese"
" Funktion ist nur für die Unternehmens-Ausgabe verfügbar. Wird "
"abgebrochen."

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:97
#, python-format
msgid "The %s app group is not listed in appsGroupsByServer"
msgstr "Die %s app Gruppe ist nicht in appsGroupsByServer aufgelistet"

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:117
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr "Ungültiger Servername: %(servername)s. Verfügbare Server: %(servers)s"

#: src/vigilo/vigiconf/lib/generators/base.py:73
msgid "Generators must define the generate_host() method"
msgstr "Generatoren müssen die generate_host() methode definieren"

#: src/vigilo/vigiconf/lib/generators/file.py:92
#, python-format
msgid "No such template: %s"
msgstr "Vorlage nicht vorhanden: %s"

#: src/vigilo/vigiconf/lib/generators/manager.py:163
msgid "Can't find the metro server for the RRD-based services"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:175
#, python-format
msgid ""
"The metrology server %s must be supervised for the RRD-based services to "
"work"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/map.py:89
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr "Die Mapgruppe %s wurde nicht vom Installationsverfahren hinzugefügt"

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr "Die 'Lade'-Methode muss neudefiniert werden"

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:115
msgid ""
"The key attribute must be defined, or the get_key() method must be "
"redefined"
msgstr ""
"Schlüsselattribut muss definiert oder die get_key() Methode muss "
"neudefiniert werden"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:99
msgid "An XSD schema should be provided for validation."
msgstr "Ein XSD Schema sollte zur Gültigkeitsprüfung bereitgestellt werden."

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:102
#, python-format
msgid "XSD file does not exist: %s"
msgstr "XSD Datei ist nicht vorhanden: %s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:198
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr "Fehler durch Abweichung des Ende-Tags: %(start)s/%(end)s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:205
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr "Syntaxfehler in \"%(path)s\": %(error)s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:366
#, python-format
msgid "Can't find an item matching %s"
msgstr "Es kann kein zu %s passendes Element gefunden werden"

#: src/vigilo/vigiconf/lib/servertypes/local.py:46
#, python-format
msgid "Can't deploy the tar archive for server %(server)s: %(error)s"
msgstr ""
"Tar-Archiv kann für Server %(server)s: %(error)s nicht bereitgestellt "
"werden"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:50
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr "SSH config Datei: %s kann nicht gefunden werden"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:87
#, python-format
msgid "The archive file does not exist: %s"
msgstr "Die Archivdatei: %s ist nicht vorhanden"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:93
#, python-format
msgid "Can't copy the configuration archive to %(server)s: %(error)s"
msgstr ""
"Das Konfigurationsarchiv kann nicht in %(server)s kopiert werden: "
"%(error)s"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:108
#, python-format
msgid "Can't deploy the configuration for server %(server)s: %(error)s"
msgstr ""
"Die Konfiguration für Server %(server)s kann nicht bereitgestellt werden:"
" %(error)s"

#: src/vigilo/vigiconf/lib/ventilation/remote.py:78
#, python-format
msgid "Can't find application %s in database"
msgstr "Die Anwendung %s kann in der Datenbank nicht gefunden werden"

#: src/vigilo/vigiconf/lib/ventilation/remote.py:167
#, python-format
msgid ""
"Could not determine how to ventilate host \"%s\". Affect some groups to "
"this host or use the ventilation attribute."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:173
#, python-format
msgid ""
"Found multiple candidates for ventilation (%(candidates)r) on "
"\"%(host)s\", use the ventilation attribute to select one."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:202
#: src/vigilo/vigiconf/lib/ventilation/remote.py:323
#: src/vigilo/vigiconf/lib/ventilation/remote.py:340
#, python-format
msgid "The Vigilo server %s does not exist"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:270
#, python-format
msgid ""
"No server available for the appgroup %(appgroup)s and the hostgroup "
"%(hostgroup)s, skipping it"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:326
#, python-format
msgid "The Vigilo server %s is already disabled"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:343
#, python-format
msgid "The Vigilo server %s is already enabled"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:99
#, python-format
msgid "Unknown group \"%(group)s\" in HLS \"%(hls)s\"."
msgstr "Unbekannte Gruppe \"%(group)s\" in HLS \"%(hls)s\"."

#: src/vigilo/vigiconf/loaders/hlservice.py:133
#, python-format
msgid "Invalid operator \"%(operator)s\". Possible values: %(possibilities)s"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:179
#, python-format
msgid ""
"syntax error in HLS %(hls)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""
"Syntaxfehler in HLS %(hls)s: Es konnte keine zu diesem Pfad : "
"\"%(path)s\" passende Gruppe gefunden werden"

#: src/vigilo/vigiconf/loaders/host.py:70
#, python-format
msgid "Deleting leftover config file from database: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:76
#, python-format
msgid "Loading hosts"
msgstr "Hosts werden geladen"

#: src/vigilo/vigiconf/loaders/host.py:127
#, python-format
msgid "Loading host %s"
msgstr "Host %s wird geladen"

#: src/vigilo/vigiconf/loaders/host.py:179
msgid "Cleaning up old hosts"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:236
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr "Unbekannte Gruppe \"%(group)s\" in Host \"%(host)s\"."

#: src/vigilo/vigiconf/loaders/host.py:263
#, python-format
msgid ""
"syntax error in host %(host)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""
"Syntaxfehler in Host %(host)s: Es konnte keine zu diesem Pfad : "
"\"%(path)s\" passende Gruppe gefunden werden"

#: src/vigilo/vigiconf/loaders/topology.py:102
#, python-format
msgid "Not a Dependency: %s"
msgstr "Keine Abhängigkeit: %s"

#: src/vigilo/vigiconf/loaders/topology.py:117
msgid "No dependent supervised item"
msgstr "Kein abhängiges überwachtes Element"

#~ msgid "Service group %s does not exist."
#~ msgstr "Servicegruppe %s ist nicht vorhanden."

