# German translations for vigilo-vigiconf.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 13:19+0100\n"
"PO-Revision-Date: 2011-02-23 08:43+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:74
#, python-format
msgid "ERROR: %s"
msgstr "FEHLER: %s"

#: src/vigilo/vigiconf/commandline.py:77
msgid "No server to manage."
msgstr "Kein Server zur Verwaltung."

#: src/vigilo/vigiconf/commandline.py:143
msgid ""
"Vigilo server management is only available in the Enterprise edition. "
"Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:167
msgid "usage: "
msgstr "Verwendung: "

#: src/vigilo/vigiconf/commandline.py:168
#, python-format
msgid "conflicting option string(s): %s"
msgstr "widersprüchliche Option String(s): %s"

#: src/vigilo/vigiconf/commandline.py:169
msgid "subcommands"
msgstr "Unterbefehle"

#: src/vigilo/vigiconf/commandline.py:170
#, python-format
msgid "unrecognized arguments: %s"
msgstr "Unbekannte Argumente: %s"

#: src/vigilo/vigiconf/commandline.py:171
msgid "expected one argument"
msgstr "ein Argument erwartet"

#: src/vigilo/vigiconf/commandline.py:172
msgid "expected at most one argument"
msgstr "höchstens ein Argument erwartet"

#: src/vigilo/vigiconf/commandline.py:173
msgid "expected at least one argument"
msgstr "mindestens ein Argument erwartet"

#: src/vigilo/vigiconf/commandline.py:174
#, python-format
msgid "expected %s argument(s)"
msgstr "%s Argument(e) erwartet"

#: src/vigilo/vigiconf/commandline.py:175
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr "ungültige Auswahl: %r (gewählt aus %s)"

#: src/vigilo/vigiconf/commandline.py:176
msgid "positional arguments"
msgstr "positionale Argumente"

#: src/vigilo/vigiconf/commandline.py:177
msgid "optional arguments"
msgstr "optionale Argumente"

#: src/vigilo/vigiconf/commandline.py:178
msgid "too few arguments"
msgstr "zu wenig Argumente"

#: src/vigilo/vigiconf/commandline.py:179
#, python-format
msgid "argument %s is required"
msgstr "Argument %s erforderlich"

#: src/vigilo/vigiconf/commandline.py:180
#, python-format
msgid "one of the arguments %s is required"
msgstr "eines der Argumente %s ist erforderlich"

#: src/vigilo/vigiconf/commandline.py:181
#, python-format
msgid "%s: error: %s\n"
msgstr "%s: Fehler: %s\n"

#: src/vigilo/vigiconf/commandline.py:182
msgid "show this help message and exit"
msgstr "Diese Hilfemeldung anzeigen und beenden"

#: src/vigilo/vigiconf/commandline.py:183
msgid "show program's version number and exit"
msgstr "Versionsnummer des Programms anzeigen und beenden"

#: src/vigilo/vigiconf/commandline.py:187
msgid "Debug mode."
msgstr "Debug-Modus."

#: src/vigilo/vigiconf/commandline.py:189
msgid "Don't try to switch to the correct user."
msgstr "Nicht versuchen, zum korrekten Benutzer zu wechseln."

#: src/vigilo/vigiconf/commandline.py:194
msgid "Vigilo configuration manager"
msgstr "Vigilo Konfigurationsmanager"

#: src/vigilo/vigiconf/commandline.py:195
msgid "Subcommands"
msgstr "Unterbefehle"

#: src/vigilo/vigiconf/commandline.py:201
msgid "Prints a summary of the current configuration."
msgstr "Druckt eine Übersicht der aktuellen Konfiguration."

#: src/vigilo/vigiconf/commandline.py:204
msgid "Supervision servers to query, all of them if not specified."
msgstr "Abzufragender Kontrollserver, alle, wenn nicht angegeben."

#: src/vigilo/vigiconf/commandline.py:248
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""
"Stellt die Konfiguration auf jedem Server bereit, wenn sich die "
"Konfiguration geändert hat."

#: src/vigilo/vigiconf/commandline.py:252
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""
"Den Prozess nach Dateierstellung beenden, bevor die Datein verschoben "
"werden."

#: src/vigilo/vigiconf/commandline.py:255
msgid ""
"Stop after pushing the files to the remote servers, and before restarting"
" the services."
msgstr ""
"Nach Verschieben der Datein zum Remoteserver und vor erneutem Start von "
"Services beenden."

#: src/vigilo/vigiconf/commandline.py:258
msgid "Deploy the given revision"
msgstr "Gegebene Revision bereitstellen"

#: src/vigilo/vigiconf/commandline.py:260
msgid ""
"Force the immediate execution of the command. Do not wait. Bypass all "
"checks."
msgstr ""
"Sofortige Ausführung des Befehls erzwingen. Nicht warten. Alle Prüfungen "
"umgehen."

#: src/vigilo/vigiconf/commandline.py:263
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""
"Nur Simulation, es wird keine Kopie wirklich erstellt, kein Commit in der"
" Datenbank."

#: src/vigilo/vigiconf/commandline.py:266
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr "Kontrollserver zur Bereitstellung, alle, wenn nicht angegeben."

#: src/vigilo/vigiconf/commandline.py:273
msgid "Discover the services available on a remote server."
msgstr "Services eines Remoteserver entdecken ."

#: src/vigilo/vigiconf/commandline.py:278
msgid "Output file. Default: standard output."
msgstr "Ausgabedatei. Standardmäßig: Standardausgabe."

#: src/vigilo/vigiconf/commandline.py:280
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr "SNMP Community. Fehler: %(default)s."

#: src/vigilo/vigiconf/commandline.py:282
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr "SNMP Version. Fehler: %(default)s."

#: src/vigilo/vigiconf/commandline.py:284
#, python-format
msgid "Main group. Default: %(default)s."
msgstr "Hauptgruppe. Fehler: %(default)s."

#: src/vigilo/vigiconf/commandline.py:286
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk "
"command on the '.1' OID with the '-OnQe' options."
msgstr ""
"Zu scannende Hosts oder Datein. Die Datein müssen das Ergebnis eines "
"snmpwalk Befehls auf '.1' OID mit den  '-OnQe' Optionen sein."

#: src/vigilo/vigiconf/commandline.py:294
msgid "Enables or disables a Vigilo server"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:297
msgid "Don't re-deploy the configuration, only set the status."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:300
msgid "New status"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:302
msgid "Server name(s) to enable/disable"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:313
msgid ""
"VigiConf was launched as user 'root'. Switching to user 'vigiconf' "
"instead."
msgstr ""
"VigiConf wurde als Benutzer 'root' gestartet. Stattdessen zu Benutzer "
"'vigiconf' wechseln."

#: src/vigilo/vigiconf/commandline.py:318
msgid "Unable to switch to user 'vigiconf'. Aborting."
msgstr "Es kann nicht zu Benutzer 'vigiconf' gewechselt werden. Wird abgebrochen."

#: src/vigilo/vigiconf/commandline.py:342
msgid "VigiConf was not launched as user 'vigiconf'. Aborting."
msgstr "VigiConf wurde nicht als Benutzer 'vigiconf' gestartet. Wird abgebrochen."

#: src/vigilo/vigiconf/commandline.py:375
#, python-format
msgid ""
"Can't obtain lock on lockfile (%(lockfile)s). VigiConf already running ? "
"REASON : %(error)s"
msgstr ""
"Keine Sperre bei dieser Lock-Datei (%(lockfile)s) möglich. Wurde VigiConf"
" schon gestartet ? URSACHE: %(error)s"

#: src/vigilo/vigiconf/commandline.py:388
#: src/vigilo/vigiconf/commandline.py:390
#, python-format
msgid "VigiConf error: %s"
msgstr "VigiConf Fehler: %s"

#: src/vigilo/vigiconf/commandline.py:394
msgid "VigiConf is done."
msgstr ""

#: src/vigilo/vigiconf/conf.py:74
msgid "Loading XML configuration"
msgstr "XML Konfiguration wird geladen"

#: src/vigilo/vigiconf/conf.py:79
msgid "Error loading configuration"
msgstr "Fehler beim Laden der Konfiguration"

#: src/vigilo/vigiconf/discoverator.py:78
#, python-format
msgid "%s: No such file"
msgstr "%s: Datei nicht vorhanden"

#: src/vigilo/vigiconf/discoverator.py:90
#, python-format
msgid ""
"Invalid HOSTNAME detected in SNMPv2-MIB::sysName.0: \"%s\" (blank "
"character not allowed)"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:125
msgid "The \"snmpwalk\" command is not installed."
msgstr "Der \"snmpwalk\"-Befehl ist nicht installiert."

#: src/vigilo/vigiconf/discoverator.py:128
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)s"
msgstr ""
"Fehlschlagen des SNMP Laufbefehls mit Status %(status)s und Meldung:\n"
"\"\n"
"\"%(msg)s\n"
"\"\n"
"\"Befehl war: %(cmd)s"

#: src/vigilo/vigiconf/applications/nagios_hls/generator.py:71
msgid "No server has been configured to host High-Level Services"
msgstr "Es wurde kein Server konfiguriert, um High-Level Services zu beherbergen"

#: src/vigilo/vigiconf/applications/vigirrd/generator.py:83
#, python-format
msgid "Some datasources are not on a graph: %s"
msgstr ""

#: src/vigilo/vigiconf/connector/command.py:28
msgid "An instance of Command can only be run once"
msgstr ""

#: src/vigilo/vigiconf/connector/command.py:94
#, python-format
msgid "VigiConf finished properly (duration: %ds)"
msgstr ""

#: src/vigilo/vigiconf/connector/command.py:99
#, python-format
msgid "VigiConf failed ! Exit code: %(rcode)d, duration: %(duration)ds"
msgstr ""

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:45
#, python-format
msgid "Recieved unhandled message type: %(msgtype)s"
msgstr ""

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:75
#, python-format
msgid "Running command: %s"
msgstr ""

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:81
msgid "FAILED!"
msgstr ""

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:84
msgid "OK."
msgstr ""

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:85
#, python-format
msgid "Duration: %d seconds"
msgstr ""

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:155
#, python-format
msgid "Accepting subscription request from %s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:159
#, python-format
msgid "Can't find the validation script for app %(app)s: %(error)s"
msgstr ""
"Gültigkeitsprüfungsskript für app %(app)s kann nicht gefunden werden: "
"%(error)s"

#: src/vigilo/vigiconf/lib/application.py:275
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr ""
"%(app)s: Gültigkeitsprüfung für Server '%(server)s' fehlgeschlagen: "
"%(reason)s"

#: src/vigilo/vigiconf/lib/application.py:282
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr "%(app)s : Gültigkeitsprüfung für Server erfolgreich: %(server)s"

#: src/vigilo/vigiconf/lib/application.py:303
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr ""
"%(app)s : Qualifikation bei '%(server)s' fehlgeschlagen - URSACHE: "
"%(reason)s"

#: src/vigilo/vigiconf/lib/application.py:312
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr "%(app)s : Qualifikation bei Server erfolgreich: %(server)s"

#: src/vigilo/vigiconf/lib/application.py:325
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr "%(app)s wird auf %(server)s gestartet..."

#: src/vigilo/vigiconf/lib/application.py:335
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr "%(app)s auf %(server)s kann nicht gestartet werden - URSACHE %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:343
#, python-format
msgid "%(app)s started on %(server)s"
msgstr "%(app)s auf %(server)s gestartet"

#: src/vigilo/vigiconf/lib/application.py:357
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr "%(app)s auf %(server)s werden beendet ..."

#: src/vigilo/vigiconf/lib/application.py:367
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr "%(app)s auf %(server)s kann nicht beendet werden - URSACHE %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:375
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr "%(app)s auf %(server)s beendet"

#: src/vigilo/vigiconf/lib/application.py:407
#, python-format
msgid "%(app)s: %(action)s process failed."
msgstr "%(app)s : %(action)s fehlgeschlagen."

#: src/vigilo/vigiconf/lib/dispatchator.py:138
#, python-format
msgid ""
"Incoherent configuration: application %(app)s has an entry point named "
"%(epname)s in package %(eppkg)s"
msgstr ""
"Inkohärente Konfiguration: Anwendung %(app)s hat einen Einstiegspunkt "
"namens %(epname)s im Paket %(eppkg)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:143
#, python-format
msgid "Application %s is installed but disabled (see conf.d/general/apps.py)"
msgstr ""
"Anwendung %s ist installiert, jedoch deaktiviert (siehe "
"conf.d/general/apps.py)"

#: src/vigilo/vigiconf/lib/dispatchator.py:147
#, python-format
msgid "application %s is not unique."
msgstr "Anwendung %s ist nicht eindeutig."

#: src/vigilo/vigiconf/lib/dispatchator.py:148
#, python-format
msgid " Providing modules: %s"
msgstr " Module: %s werden bereitgestellt"

#: src/vigilo/vigiconf/lib/dispatchator.py:158
#, python-format
msgid ""
"Application %s has been added to conf.d/general/apps.py, but is not "
"installed"
msgstr ""
"Anwendung %s wurde zu conf.d/general/apps.py hinzugefügt, ist jedoch "
"nicht installiert"

#: src/vigilo/vigiconf/lib/dispatchator.py:183
msgid "Generation failed!"
msgstr "Generierung fehlgeschlagen!"

#: src/vigilo/vigiconf/lib/dispatchator.py:186
msgid "Generation successful"
msgstr "Generierung erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:193
msgid "SVN commit successful"
msgstr "SVN commit erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:206
msgid "validation failed, see above for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:208
msgid "Validation successful"
msgstr "Gültigkeitsprüfung erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:218
msgid ""
"you can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""
"Sie können nicht zu einer früheren Revision zurückkehren, wenn Sie Ihre "
"Konfiguration geändert haben. 'svn revert' verwenden, um Änderungen "
"rückgängig zu machen"

#: src/vigilo/vigiconf/lib/dispatchator.py:234
#, python-format
msgid "can't get the SVN status for the configuration dir: %s"
msgstr "der SVN Status für die Konfiguration dir: %s kann nicht erhalten werden"

#: src/vigilo/vigiconf/lib/dispatchator.py:264
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""
"Kann nicht aktualisiert werden, da der Konfigurationsparameter "
"'svnrepository' leer ist"

#: src/vigilo/vigiconf/lib/dispatchator.py:287
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr "%(path)s kann dem Repository nicht hinzugefügt werden: %(error)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:305
#, python-format
msgid "can't remove %(path)s from repository: %(error)s"
msgstr "%(path)s kann nicht aus dem Repository entfernt werden: %(error)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:313
msgid ""
"Not committing because the 'svnrepository' configuration parameter is "
"empty"
msgstr ""
"Commit wird nicht ausgeführt, das der Konfigurationsparameter "
"'svnrepository' leer ist"

#: src/vigilo/vigiconf/lib/dispatchator.py:325
#, python-format
msgid "can't commit the configuration dir in SVN: %s"
msgstr "Commit kann für die Konfiguration dir in SVN nicht ausgeführt werden: %s"

#: src/vigilo/vigiconf/lib/dispatchator.py:340
#, python-format
msgid ""
"can't execute the request to update the local copy. COMMAND %(cmd)s "
"FAILED. REASON: %(reason)s"
msgstr ""
"die Anforderung der Aktualisierung der lokalen Kopie kann nicht "
"ausgeführt werden. BEFEHL %(cmd)s FEHLGESCHLAGEN. URSACHE: %(reason)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:382
#, python-format
msgid "can't execute the request to get the current revision: %s"
msgstr ""
"die Anforderung die aktuelle Revision: %s zu erhalten kann nicht "
"ausgeführt werden"

#: src/vigilo/vigiconf/lib/dispatchator.py:425
msgid ""
"The configurations files have not been transfered on every server. See "
"above for more information."
msgstr ""
"Die Konfigurationsdatein wurden nicht auf alle Server übertragen. Weitere"
" Informationen siehe oben."

#: src/vigilo/vigiconf/lib/dispatchator.py:459
msgid "qualification failed. See above for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:461
msgid "Qualification successful"
msgstr "Gültigkeitsprüfung erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:485
msgid "All servers are up-to-date, no deployment needed."
msgstr "Alle Server sind aktualisiert. Kein Bereitstellung erforderlich."

#: src/vigilo/vigiconf/lib/dispatchator.py:494
msgid "Database commit successful"
msgstr "Datenbank commit erfolgreich"

#: src/vigilo/vigiconf/lib/dispatchator.py:498
msgid "Database commit failed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:546
msgid "Switch directories was not successful on each server."
msgstr "Wechseln der Verzeichnisse war nicht auf jedem Server erfolgreich."

#: src/vigilo/vigiconf/lib/dispatchator.py:573
msgid "Stop applications failed"
msgstr "Beenden der Anwendungen fehlgeschlagen"

#: src/vigilo/vigiconf/lib/dispatchator.py:586
msgid "Start applications failed"
msgstr "Starten der Anwendungen fehlgeschlagen"

#: src/vigilo/vigiconf/lib/dispatchator.py:600
msgid "All servers are up-to-date. No restart needed."
msgstr "Alle Server sind aktualisiert. Kein Neustart erforderlich."

#: src/vigilo/vigiconf/lib/dispatchator.py:610
#, python-format
msgid "Current revision in the repository : %d"
msgstr "Aktuelle Revision im Repository : %d"

#: src/vigilo/vigiconf/lib/dispatchator.py:618
msgid "(should be deployed)"
msgstr "(sollte bereitgestellt werden)"

#: src/vigilo/vigiconf/lib/dispatchator.py:620
msgid "(should restart)"
msgstr "(sollte neustarten)"

#: src/vigilo/vigiconf/lib/dispatchator.py:621
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr "Revisionen für Server %(server)s : %(rev)s%(dep)s%(restart)s"

#: src/vigilo/vigiconf/lib/dispatchator.py:627
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""
"Für den Server: %(server)s kann keine Revision erhalten werden. URSACHE :"
" %(reason)s"

#: src/vigilo/vigiconf/lib/remotecommand.py:117
msgid "Server name set to None."
msgstr "Servername auf Keiner gesetzt."

#: src/vigilo/vigiconf/lib/remotecommand.py:119
msgid "Server name incorrect (length = 0)."
msgstr "Servername ungültig  (Länge = 0)."

#: src/vigilo/vigiconf/lib/remotecommand.py:179
msgid "Unknown command type."
msgstr "Unbekannter Befehlstyp."

#: src/vigilo/vigiconf/lib/remotecommand.py:196
#, python-format
msgid "The source file does not exist: %s"
msgstr "Die Quelldatei ist nicht vorhanden: %s"

#: src/vigilo/vigiconf/lib/remotecommand.py:213
#: src/vigilo/vigiconf/lib/remotecommand.py:246
msgid "Cannot reach server."
msgstr "Server kann nicht erreicht werden."

#: src/vigilo/vigiconf/lib/remotecommand.py:216
#: src/vigilo/vigiconf/lib/remotecommand.py:248
msgid "Cannot find file."
msgstr "Datei kann nicht gefunden werden."

#: src/vigilo/vigiconf/lib/revisionmanager.py:87
#, python-format
msgid "Deployed: %d"
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:88
#, python-format
msgid "Installed: %d"
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:89
#, python-format
msgid "Previous: %d"
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:176
#, python-format
msgid "Cannot write the revision file: %s"
msgstr "Revisionsdatei: %s kann nicht beschrieben werden"

#: src/vigilo/vigiconf/lib/server.py:83
msgid "On the Community Edition, you can only use localhost"
msgstr "Auf der Community Ausgabe, kann nur der Lokalhost benutzt werden"

#: src/vigilo/vigiconf/lib/server.py:178
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""
"Die Konfiguration auf %(server)s kann nicht aktiviert werden. BEFEHL "
"%(cmd)s FEHLGESCHLAGEN. URSACHE: %(reason)s"

#: src/vigilo/vigiconf/lib/server.py:204
#, python-format
msgid "Can't tar config for server %(server)s: %(error)s"
msgstr "Konfig kann für Server %(server)s nicht archiviert werden: %(error)s"

#: src/vigilo/vigiconf/lib/server.py:222
#, python-format
msgid "%s : deployement successful."
msgstr "%s : erfolgreich bereitgestellt."

#: src/vigilo/vigiconf/lib/server.py:240
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr "Datein (%(from)s können nicht in %(to)s) kopiert werden: %(error)s."

#: src/vigilo/vigiconf/lib/systemcommand.py:52
#, python-format
msgid "Command \"%(cmd)s\" failed with code %(code)s and message: %(msg)s"
msgstr "Befehl %(cmd)s fehlgeschlagen mit Code %(code)s und Meldung: %(msg)s"

#: src/vigilo/vigiconf/lib/validator.py:125
msgid "No server configuration to be generated"
msgstr "Keine zu erstellende Serverkonfiguration"

#: src/vigilo/vigiconf/lib/validator.py:128
msgid "No application configuration to be generated"
msgstr "Keine zu erstellende Anwendungskonfiguration"

#: src/vigilo/vigiconf/lib/validator.py:131
msgid "No host configuration to be generated"
msgstr "Keine zu erstellende Hostkonfiguration"

#: src/vigilo/vigiconf/lib/validator.py:139
#, python-format
msgid ""
"The number of host entries in the database does not match the number of "
"hosts in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:167
#, python-format
msgid ""
"The number of services entries in the database does not match the number "
"of services in the configuration. Database: %(db)d, configuration: "
"%(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:181
#, python-format
msgid ""
"The number of apps loaded in the database does not match the number of "
"apps to deploy. Database: %(db)d, to deploy: %(deploy)d. Possible cause: "
"one or more app have no Vigilo server to be deployed on."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:199
#, python-format
msgid ""
"The number of ventilation entries in the database does not match the "
"number of host and apps. Database: %(db)d, should be: %(conf)d. Possible "
"cause: one or more application have no Vigilo server to be deployed on."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:233
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""
"%(nb_gens)d Generatoren sind vorhanden und %(nb_apps)d Anwendungen sind "
"konfiguriert worden"

#: src/vigilo/vigiconf/lib/validator.py:240
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr "########> Fehler in %(source)s (object %(object)s): %(error)s"

#: src/vigilo/vigiconf/lib/validator.py:247
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr "====> Warnung in %(source)s (object %(object)s): %(error)s"

#: src/vigilo/vigiconf/lib/validator.py:253
#, python-format
msgid "%d errors"
msgstr "%d Fehler"

#: src/vigilo/vigiconf/lib/validator.py:254
#, python-format
msgid "%d warnings"
msgstr "%d Warnungen"

#: src/vigilo/vigiconf/lib/validator.py:256
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""
"%(nbGenerators)d Generatoren haben %(nbHosts)d Hosts auf %(nbServers)d "
"Servern konfiguriert."

#: src/vigilo/vigiconf/lib/validator.py:258
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr "%(filesWritten)d Datein wurden in %(dirsCreated)d Verzeichnissen erstellt"

#: src/vigilo/vigiconf/lib/confclasses/host.py:136
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:159
#, python-format
msgid "The \"%s\" attribute has been deprecated. Please use \"%s\" instead."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:185
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""
"Test \"%(test_name)s\" auf \"%(host)s\" benötigt die folgenden Argumente:"
" %(args)s (and only those)"

#: src/vigilo/vigiconf/lib/confclasses/host.py:541
#, python-format
msgid "Wrong datasource in graph '%(graph)s': %(ds)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:781
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:287
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:115
#, python-format
msgid "Not enough memory to validate %(file)s using schema %(schema)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:788
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:294
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:122
#, python-format
msgid "Invalid XML validation schema %(schema)s found while validating %(file)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:795
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:301
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:129
#, python-format
msgid "XML validation failed (%(file)s with schema %(schema)s)"
msgstr "XML Gültigkeitsprüfung (%(file)s mit Schema %(schema)s) fehlgeschlagen"

#: src/vigilo/vigiconf/lib/confclasses/host.py:800
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:306
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:134
#, python-format
msgid ""
"XML validation failed for file %(file)s, using schema %(schema)s, due to "
"an error. Make sure the permissions are set correctly."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:848
#, python-format
msgid "Invalid ventilation group: %s"
msgstr "Ungültige Aufteilungsgruppe: %s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:882
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr "Ungültiger Gewichtungswert für Test %(test)s auf Host %(host)s: %(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/host.py:930
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:119
#: src/vigilo/vigiconf/loaders/hlservice.py:143
#, python-format
msgid "Invalid group name (%s)"
msgstr "Ungültiger Gruppenname (%s)"

#: src/vigilo/vigiconf/lib/confclasses/host.py:939
#, python-format
msgid "Invalid weight value for host %(host)s: %(weight)r"
msgstr "Ungültiger Gewichtungswert für Host %(host)s: %(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/host.py:952
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr "Host \"%s\" muss mindestens einer Gruppe zugeordnet werden."

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:385
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""
"Ungültiger Gewichtungswert für Test %(test)s in Vorlage %(tpl)s: "
"%(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:407
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr "Ungültiger Gewichtungswert für Vorlage %(tpl)s: %(weight)r"

#: src/vigilo/vigiconf/lib/dispatchmodes/__init__.py:54
msgid ""
"You are trying remote deployment on the Community edition. This feature "
"is only available in the Enterprise edition. Aborting."
msgstr ""
"Sie versuchen eine Remote-Bereitstellung bei der Community Ausgabe. Diese"
" Funktion ist nur für die Unternehmens-Ausgabe verfügbar. Wird "
"abgebrochen."

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:91
#, python-format
msgid "The %s app group is not listed in appsGroupsByServer"
msgstr "Die %s app Gruppe ist nicht in appsGroupsByServer aufgelistet"

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:111
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr "Ungültiger Servername: %(servername)s. Verfügbare Server: %(servers)s"

#: src/vigilo/vigiconf/lib/generators/base.py:79
msgid "Generators must define the generate_host() method"
msgstr "Generatoren müssen die generate_host() methode definieren"

#: src/vigilo/vigiconf/lib/generators/file.py:96
#, python-format
msgid "No such template: %s"
msgstr "Vorlage nicht vorhanden: %s"

#: src/vigilo/vigiconf/lib/generators/manager.py:100
#: src/vigilo/vigiconf/lib/generators/manager.py:310
#, python-format
msgid "Generated configuration for %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:129
msgid "Computing ventilation"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:144
msgid "Running generators"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:166
#, python-format
msgid "Generating configuration for %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:172
msgid "Running database generators"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:185
#, python-format
msgid "%(errtype)s in application %(app)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:206
msgid "Can't find the metro server for the RRD-based services"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:218
#: src/vigilo/vigiconf/lib/generators/manager.py:228
#, python-format
msgid ""
"The metrology server %s must be supervised for the RRD-based services to "
"work"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/map.py:78
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr "Die Mapgruppe %s wurde nicht vom Installationsverfahren hinzugefügt"

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr "Die 'Lade'-Methode muss neudefiniert werden"

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:115
msgid ""
"The key attribute must be defined, or the get_key() method must be "
"redefined"
msgstr ""
"Schlüsselattribut muss definiert oder die get_key() Methode muss "
"neudefiniert werden"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:99
msgid "An XSD schema should be provided for validation."
msgstr "Ein XSD Schema sollte zur Gültigkeitsprüfung bereitgestellt werden."

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:102
#, python-format
msgid "XSD file does not exist: %s"
msgstr "XSD Datei ist nicht vorhanden: %s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:198
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr "Fehler durch Abweichung des Ende-Tags: %(start)s/%(end)s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:205
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr "Syntaxfehler in \"%(path)s\": %(error)s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:370
#, python-format
msgid "Can't find an item matching %s"
msgstr "Es kann kein zu %s passendes Element gefunden werden"

#: src/vigilo/vigiconf/lib/servertypes/local.py:46
#, python-format
msgid "Can't deploy the tar archive for server %(server)s: %(error)s"
msgstr ""
"Tar-Archiv kann für Server %(server)s: %(error)s nicht bereitgestellt "
"werden"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:50
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr "SSH config Datei: %s kann nicht gefunden werden"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:87
#, python-format
msgid "The archive file does not exist: %s"
msgstr "Die Archivdatei: %s ist nicht vorhanden"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:93
#, python-format
msgid "Can't copy the configuration archive to %(server)s: %(error)s"
msgstr ""
"Das Konfigurationsarchiv kann nicht in %(server)s kopiert werden: "
"%(error)s"

#: src/vigilo/vigiconf/lib/servertypes/remote.py:108
#, python-format
msgid "Can't deploy the configuration for server %(server)s: %(error)s"
msgstr ""
"Die Konfiguration für Server %(server)s kann nicht bereitgestellt werden:"
" %(error)s"

#: src/vigilo/vigiconf/lib/ventilation/remote.py:147
#, python-format
msgid ""
"Could not determine how to ventilate host \"%s\". Affect some groups to "
"this host or use the ventilation attribute."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:153
#, python-format
msgid ""
"Found multiple candidates for ventilation (%(candidates)r) on "
"\"%(host)s\", use the ventilation attribute to select one."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:258
#, python-format
msgid ""
"No server available for the appgroup %(appgroup)s and the hostgroup "
"%(hostgroup)s, skipping it"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:271
#, python-format
msgid ""
"Trying to ventilate hostgroup %(hostgroup)s for appgroup %(appgroup)s, "
"but the mapping is not in appsGroupsByServer."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:326
#: src/vigilo/vigiconf/lib/ventilation/remote.py:342
#, python-format
msgid "The Vigilo server %s does not exist"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:329
#, python-format
msgid "The Vigilo server %s is already disabled"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:345
#, python-format
msgid "The Vigilo server %s is already enabled"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:99
#, python-format
msgid "Unknown group \"%(group)s\" in HLS \"%(hls)s\"."
msgstr "Unbekannte Gruppe \"%(group)s\" in HLS \"%(hls)s\"."

#: src/vigilo/vigiconf/loaders/hlservice.py:133
#, python-format
msgid "Invalid operator \"%(operator)s\". Possible values: %(possibilities)s"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:183
#, python-format
msgid ""
"syntax error in HLS %(hls)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""
"Syntaxfehler in HLS %(hls)s: Es konnte keine zu diesem Pfad : "
"\"%(path)s\" passende Gruppe gefunden werden"

#: src/vigilo/vigiconf/loaders/host.py:71
#, python-format
msgid "Deleting leftover config file from database: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:77
msgid "Loading hosts"
msgstr "Hosts werden geladen"

#: src/vigilo/vigiconf/loaders/host.py:128
#, python-format
msgid "Loading host %s"
msgstr "Host %s wird geladen"

#: src/vigilo/vigiconf/loaders/host.py:241
msgid "Done loading hosts"
msgstr "Hosts sind geladen"

#: src/vigilo/vigiconf/loaders/host.py:264
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr "Unbekannte Gruppe \"%(group)s\" in Host \"%(host)s\"."

#: src/vigilo/vigiconf/loaders/host.py:291
#, python-format
msgid ""
"syntax error in host %(host)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""
"Syntaxfehler in Host %(host)s: Es konnte keine zu diesem Pfad : "
"\"%(path)s\" passende Gruppe gefunden werden"

#: src/vigilo/vigiconf/loaders/topology.py:102
#, python-format
msgid "Not a Dependency: %s"
msgstr "Keine Abhängigkeit: %s"

#: src/vigilo/vigiconf/loaders/topology.py:117
msgid "No dependent supervised item"
msgstr "Kein abhängiges überwachtes Element"

#: src/vigilo/vigiconf/loaders/ventilation.py:143
#, python-format
msgid ""
"The application %s has been removed from the configuration, it needs to "
"be stopped manually"
msgstr ""

