# Translations template for vigilo-vigiconf.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-09-17 13:47+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.5\n"

#: src/vigilo/vigiconf/commandline.py:70
#, python-format
msgid "ERROR: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:73
msgid "No server to manage."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:135
msgid "usage: "
msgstr ""

#: src/vigilo/vigiconf/commandline.py:136
#, python-format
msgid "conflicting option string(s): %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:137
msgid "subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:138
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:139
msgid "expected one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:140
msgid "expected at most one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:141
msgid "expected at least one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:142
#, python-format
msgid "expected %s argument(s)"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:143
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:144
msgid "positional arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:145
msgid "optional arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:146
msgid "too few arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:147
#, python-format
msgid "argument %s is required"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:148
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:149
#, python-format
msgid "%s: error: %s\n"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:150
msgid "show this help message and exit"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:151
msgid "show program's version number and exit"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:155
msgid "Debug mode."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:157
msgid "Don't try to switch to the correct user."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:162
msgid "Vigilo configuration manager"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:163
msgid "Subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:169
msgid "Prints a summary of the current configuration."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:172
msgid "Supervision servers to query, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:179
msgid "Application status management."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:183
msgid "Stop the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:185
msgid "Start the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:187
msgid "Restart the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:189
msgid "Applications to manage, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:211
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:215
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:218
msgid ""
"Stop after pushing the files to the remote servers, and before restarting the"
" services."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:221
msgid "Deploy the given revision"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:223
msgid "Force the immediate execution of the command. Do not wait. Bypass all checks."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:226
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:229
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:236
msgid "Discover the services available on a remote server."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:241
msgid "Output file. Default: standard output."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:243
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:245
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:247
#, python-format
msgid "Main group. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:249
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk command "
"on the '.1' OID with the '-OnQe' options."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:261
msgid "VigiConf was launched as user 'root'. Switching to user 'vigiconf' instead."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:266
msgid "Unable to switch to user 'vigiconf'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:288
msgid "VigiConf was not launched as user 'vigiconf'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:301
msgid "VigiConf starting..."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:307
#, python-format
msgid "Can't obtain lock on lockfile. Dispatchator already running ? REASON : %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:314 src/vigilo/vigiconf/commandline.py:316
#, python-format
msgid "VigiConf error: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:319
msgid "VigiConf ended."
msgstr ""

#: src/vigilo/vigiconf/conf.py:298
msgid "Error loading configuration"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:80
#, python-format
msgid "%s: No such file"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:125
msgid "The \"snmpwalk\" command is not installed."
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:128
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:206
#, python-format
msgid "Unknown application: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:274
msgid "Validation Successful"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:279
msgid "Commit Successful"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:288
msgid ""
"You can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:302
#, python-format
msgid "Can't get the SVN status for the configuration dir: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:318
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:330
#, python-format
msgid "Adding a new configuration file to the repository: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:338
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:345
#, python-format
msgid "Removing an old configuration file from the repository: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:353
#, python-format
msgid "Can't remove %(path)s from repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:361
msgid "Not committing because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:373
#, python-format
msgid "Can't commit the configuration dir in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:389
#, python-format
msgid ""
"Can't execute the request to update the local copy. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:431
#, python-format
msgid "Can't execute the request to get the current revision: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:503
msgid ""
"The configurations files have not been transfered on every server. See above "
"for more information."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:545
msgid "All servers are up-to-date. Nothing to do."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:661
msgid "Switch directories was not successful on each server."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:686
#, python-format
msgid "Server %s should be deployed."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:688
msgid "All servers are up-to-date. No restart needed."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:719
msgid "Stop applications failed"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:736
msgid "Start applications failed"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:751
#, python-format
msgid "Current revision in the repository : %d"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:759
msgid "(should be deployed)"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:761
msgid "(should restart)"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:762
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:767
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/generator.py:110 src/vigilo/vigiconf/generator.py:118
msgid "Generation failed!"
msgstr ""

#: src/vigilo/vigiconf/generator.py:121 src/vigilo/vigiconf/generator.py:130
#: src/vigilo/vigiconf/generator.py:133
msgid "Transaction rollbacked"
msgstr ""

#: src/vigilo/vigiconf/generator.py:127
msgid "Transaction commited"
msgstr ""

#: src/vigilo/vigiconf/generator.py:138
msgid "Generation successful"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:209
#, python-format
msgid "Using existing MapGroup for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:212
#, python-format
msgid "Creating MapGroup for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:219
#, python-format
msgid "Using existing Map for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:222
#, python-format
msgid "Creating Map for SupItemGroup %(group)s in MapGroup %(mapgroup)s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:233
#, python-format
msgid "Removing MapGroup %s and its children"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:296
#, python-format
msgid "Removing Map for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:315
msgid "Generating maps for the host groups"
msgstr ""

#: src/vigilo/vigiconf/generators/nagios_hls.py:75
msgid "No server has been configured to host High-Level Services"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:193
#, python-format
msgid "Can't find the appgroup for app %s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:258
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:265
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:314
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:322
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:366
#: src/vigilo/vigiconf/lib/application.py:390
#, python-format
msgid "%s : Start process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:402
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:412
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:419
#, python-format
msgid "%(app)s started on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:459
#: src/vigilo/vigiconf/lib/application.py:483
#, python-format
msgid "%s : Stop process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:495
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:505
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:512
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:115
msgid "The key attribute must be defined, or the get_key() method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:128
#, python-format
msgid "Updating: %(key)s (%(class)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:147 src/vigilo/vigiconf/loaders/group.py:117
#, python-format
msgid "Inserting: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:154
#, python-format
msgid "Deleting: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:120
msgid "Server name set to None."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:122
msgid "Server name incorrect (length = 0)."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:180
msgid "Unknown command type."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:213
#: src/vigilo/vigiconf/lib/remotecommand.py:246
msgid "Cannot reach server."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:216
#: src/vigilo/vigiconf/lib/remotecommand.py:248
msgid "Cannot find file."
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:174
#, python-format
msgid "Cannot write the revision file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:80
msgid "On the Community Edition, you can only use localhost"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:176
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:202
#, python-format
msgid "Can't tar config for server %s: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:217
#, python-format
msgid "%s : deployement successful."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:231
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr ""

#: src/vigilo/vigiconf/lib/systemcommand.py:111
#, python-format
msgid "Command %(cmd)s failed with code %(code)s and message: %(msg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:113
msgid "No server configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:117
msgid "No application configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:121
msgid "No host configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:144
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:152
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:159
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:165
#, python-format
msgid "%d errors"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:166
#, python-format
msgid "%d warnings"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:168
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:170
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:95
msgid "An XSD schema should be provided for validation."
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:97
#, python-format
msgid "XSD file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:106
#, python-format
msgid "XML validation failed (%(file)s with schema %(schema)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:168
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:175
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:319
#: src/vigilo/vigiconf/lib/confclasses/host.py:635
#, python-format
msgid "Successfully parsed %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:159
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:660
#, python-format
msgid "XML validation failed for file %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:703
#, python-format
msgid "Invalid ventilation group: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:729
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:779
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:108
#, python-format
msgid "Invalid group name (%s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:788
#, python-format
msgid "Invalid weight value for host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:801
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:814
#, python-format
msgid "Loaded host %(host)s, address %(address)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:254
msgid "XML validation failed"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:327
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:349
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/__init__.py:49
msgid ""
"You are trying remote deployment on the Community edition. This feature is "
"only available in the Enterprise edition. Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:95
#, python-format
msgid "The %s app group is not listed in appsGroupsByServer"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:115
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/__init__.py:52
msgid "Generators must define the generate() method"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/map.py:86
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/local.py:46
#, python-format
msgid "Can't deploy the tar archive for server %s: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:50
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:91
#, python-format
msgid "Can't copy the config. archive to %s: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:103
#, python-format
msgid "Can't deploy the config. for server %s: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:61
#, python-format
msgid "Not a Dependency: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:105
msgid "No dependent supervised item"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:107
#, python-format
msgid "Creating dependency from %(from)s to %(to)s"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:129
#, python-format
msgid "Can't find an item matching %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:85
#, python-format
msgid "Service group %s does not exist."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:61
#, python-format
msgid "Loading host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:75
#, python-format
msgid "Loading groups for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:80
#, python-format
msgid "Loading services for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:85
#, python-format
msgid "Loading nagios conf for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:90
#, python-format
msgid "Loading perfdatasources for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:95
#, python-format
msgid "Loading graphs for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:100
msgid "Cleaning up old graphs and graphgroups"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:122
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:151
#, python-format
msgid "Could not find a group matching this path: %s"
msgstr ""

