# Translations template for vigilo-vigiconf.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-10-18 10:35+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:75
#, python-format
msgid "ERROR: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:78
msgid "No server to manage."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:140
msgid ""
"Vigilo server management is only available in the Enterprise edition. "
"Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:156
msgid "usage: "
msgstr ""

#: src/vigilo/vigiconf/commandline.py:157
#, python-format
msgid "conflicting option string(s): %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:158
msgid "subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:159
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:160
msgid "expected one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:161
msgid "expected at most one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:162
msgid "expected at least one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:163
#, python-format
msgid "expected %s argument(s)"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:164
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:165
msgid "positional arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:166
msgid "optional arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:167
msgid "too few arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:168
#, python-format
msgid "argument %s is required"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:169
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:170
#, python-format
msgid "%s: error: %s\n"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:171
msgid "show this help message and exit"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:172
msgid "show program's version number and exit"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:176
msgid "Debug mode."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:178
msgid "Don't try to switch to the correct user."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:183
msgid "Vigilo configuration manager"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:184
msgid "Subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:190
msgid "Prints a summary of the current configuration."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:193
msgid "Supervision servers to query, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:200
msgid "Application status management."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:204
msgid "Stop the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:206
msgid "Start the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:208
msgid "Restart the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:210
msgid "Applications to manage, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:232
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:236
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:239
msgid ""
"Stop after pushing the files to the remote servers, and before restarting the"
" services."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:242
msgid "Deploy the given revision"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:244
msgid "Force the immediate execution of the command. Do not wait. Bypass all checks."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:247
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:250
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:257
msgid "Discover the services available on a remote server."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:262
msgid "Output file. Default: standard output."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:264
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:266
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:268
#, python-format
msgid "Main group. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:270
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk command "
"on the '.1' OID with the '-OnQe' options."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:278
msgid "Enables or disables a Vigilo server"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:281
msgid "Don't re-deploy the configuration, only set the status."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:284
msgid "New status"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:286
msgid "Server name(s) to enable/disable"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:297
msgid "VigiConf was launched as user 'root'. Switching to user 'vigiconf' instead."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:302
msgid "Unable to switch to user 'vigiconf'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:326
msgid "VigiConf was not launched as user 'vigiconf'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:339
msgid "VigiConf starting..."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:345
#, python-format
msgid "Can't obtain lock on lockfile. Dispatchator already running ? REASON : %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:352 src/vigilo/vigiconf/commandline.py:354
#, python-format
msgid "VigiConf error: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:357
msgid "VigiConf ended."
msgstr ""

#: src/vigilo/vigiconf/conf.py:299
msgid "Error loading configuration"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:80
#, python-format
msgid "%s: No such file"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:125
msgid "The \"snmpwalk\" command is not installed."
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:128
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)s"
msgstr ""

#: src/vigilo/vigiconf/applications/nagios_hls/generator.py:71
msgid "No server has been configured to host High-Level Services"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:189
#, python-format
msgid "Using existing MapGroup for group %s"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:192
#, python-format
msgid "Creating MapGroup for group %s"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:199
#, python-format
msgid "Using existing Map for group %s"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:202
#, python-format
msgid "Creating Map for SupItemGroup %(group)s in MapGroup %(mapgroup)s"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:212
#, python-format
msgid "Removing MapGroup %s and its children"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:275
#, python-format
msgid "Removing Map for group %s"
msgstr ""

#: src/vigilo/vigiconf/applications/vigimap/generator.py:295
msgid "Generating maps for the host groups"
msgstr ""

#: src/vigilo/vigiconf/lib/__init__.py:65
#, python-format
msgid "Skipping \"%(item)s\": (version conflict \"%(error)s\")"
msgstr ""

#: src/vigilo/vigiconf/lib/__init__.py:70
#, python-format
msgid "Skipping \"%(item)s\": (unknown extra \"%(error)s\")"
msgstr ""

#: src/vigilo/vigiconf/lib/__init__.py:75
#, python-format
msgid "Skipping \"%(item)s\": (can't import \"%(error)s\")"
msgstr ""

#: src/vigilo/vigiconf/lib/__init__.py:80
#, python-format
msgid "Skipping \"%(item)s\": (error \"%(error)s\")"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:224
#, python-format
msgid "Can't find the validation script for app %(app)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:262
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:269
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:315
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:323
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:367
#: src/vigilo/vigiconf/lib/application.py:391
#, python-format
msgid "%s : Start process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:403
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:412
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:420
#, python-format
msgid "%(app)s started on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:460
#: src/vigilo/vigiconf/lib/application.py:484
#, python-format
msgid "%s : Stop process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:496
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:505
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:513
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:168
#, python-format
msgid ""
"Incoherent configuration: application %(app)s has an entry point named "
"%(epname)s in package %(eppkg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:173
#, python-format
msgid "Application %s is installed but disabled (see conf.d/general/apps.py)"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:177
#, python-format
msgid "Application %s is not unique."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:178
#, python-format
msgid " Providing modules: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:187
#, python-format
msgid "Application %s has been added to conf.d/general/apps.py, but is not installed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:240
msgid "Validation Successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:245
msgid "Commit Successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:254
msgid ""
"You can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:268
#, python-format
msgid "Can't get the SVN status for the configuration dir: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:284
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:296
#, python-format
msgid "Adding a new configuration file to the repository: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:304
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:311
#, python-format
msgid "Removing an old configuration file from the repository: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:319
#, python-format
msgid "Can't remove %(path)s from repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:327
msgid "Not committing because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:339
#, python-format
msgid "Can't commit the configuration dir in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:354
#, python-format
msgid ""
"Can't execute the request to update the local copy. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:396
#, python-format
msgid "Can't execute the request to get the current revision: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:468
msgid ""
"The configurations files have not been transfered on every server. See above "
"for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:508
#: src/vigilo/vigiconf/lib/dispatchator.py:652
#, python-format
msgid "Server %s should be deployed."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:511
msgid "All servers are up-to-date. Nothing to do."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:627
msgid "Switch directories was not successful on each server."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:654
msgid "All servers are up-to-date. No restart needed."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:685
msgid "Stop applications failed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:702
msgid "Start applications failed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:707
#, python-format
msgid "Current revision in the repository : %d"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:715
msgid "(should be deployed)"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:717
msgid "(should restart)"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:718
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:723
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:117
msgid "Server name set to None."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:119
msgid "Server name incorrect (length = 0)."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:179
msgid "Unknown command type."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:196
#, python-format
msgid "The source file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:213
#: src/vigilo/vigiconf/lib/remotecommand.py:246
msgid "Cannot reach server."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:216
#: src/vigilo/vigiconf/lib/remotecommand.py:248
msgid "Cannot find file."
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:173
#, python-format
msgid "Cannot write the revision file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:83
msgid "On the Community Edition, you can only use localhost"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:178
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:204
#, python-format
msgid "Can't tar config for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:222
#, python-format
msgid "%s : deployement successful."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:236
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr ""

#: src/vigilo/vigiconf/lib/systemcommand.py:108
#, python-format
msgid "Command %(cmd)s failed with code %(code)s and message: %(msg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:113
msgid "No server configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:117
msgid "No application configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:121
msgid "No host configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:144
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:152
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:159
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:165
#, python-format
msgid "%d errors"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:166
#, python-format
msgid "%d warnings"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:168
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:170
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:160
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:646
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:323
#, python-format
msgid "Successfully parsed %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:671
#, python-format
msgid "XML validation failed for file %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:714
#, python-format
msgid "Invalid ventilation group: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:740
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:785
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:108
#: src/vigilo/vigiconf/loaders/hlservice.py:86
#, python-format
msgid "Invalid group name (%s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:794
#, python-format
msgid "Invalid weight value for host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:807
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:820
#, python-format
msgid "Loaded host %(host)s, address %(address)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:254
msgid "XML validation failed"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:327
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:349
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/__init__.py:54
msgid ""
"You are trying remote deployment on the Community edition. This feature is "
"only available in the Enterprise edition. Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:95
#, python-format
msgid "The %s app group is not listed in appsGroupsByServer"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:115
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/base.py:73
msgid "Generators must define the generate_host() method"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/file.py:93
#, python-format
msgid "No such template: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:106
#: src/vigilo/vigiconf/lib/generators/manager.py:115
msgid "Generation failed!"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:118
#: src/vigilo/vigiconf/lib/generators/manager.py:127
#: src/vigilo/vigiconf/lib/generators/manager.py:131
msgid "Transaction rollbacked"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:124
msgid "Transaction commited"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:136
msgid "Generation successful"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/map.py:90
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:115
msgid "The key attribute must be defined, or the get_key() method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:128
#, python-format
msgid "Updating: %(key)s (%(class)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:147
#: src/vigilo/vigiconf/loaders/group.py:117
#, python-format
msgid "Inserting: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:154
#, python-format
msgid "Deleting: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:99
msgid "An XSD schema should be provided for validation."
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:101
#, python-format
msgid "XSD file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:110
#, python-format
msgid "XML validation failed (%(file)s with schema %(schema)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:172
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:179
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:345
#, python-format
msgid "Can't find an item matching %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/local.py:46
#, python-format
msgid "Can't deploy the tar archive for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:50
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:87
#, python-format
msgid "The archive file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:93
#, python-format
msgid "Can't copy the configuration archive to %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:108
#, python-format
msgid "Can't deploy the configuration for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:72
#, python-format
msgid "Can't find application %s in database"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:182
#: src/vigilo/vigiconf/lib/ventilation/remote.py:258
#: src/vigilo/vigiconf/lib/ventilation/remote.py:275
#, python-format
msgid "The Vigilo server %s does not exist"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:261
#, python-format
msgid "The Vigilo server %s is already disabled"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:278
#, python-format
msgid "The Vigilo server %s is already enabled"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:104
#, python-format
msgid "Service group %s does not exist."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:60
#, python-format
msgid "Loading host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:74
#, python-format
msgid "Loading groups for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:79
#, python-format
msgid "Loading services for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:84
#, python-format
msgid "Loading nagios conf for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:89
#, python-format
msgid "Loading perfdatasources for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:94
#, python-format
msgid "Loading graphs for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:99
msgid "Cleaning up old graphs and graphgroups"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:121
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:150
#, python-format
msgid "syntax error in host %s: could not find a group matching path \"%s\""
msgstr ""

#: src/vigilo/vigiconf/loaders/topology.py:61
#, python-format
msgid "Not a Dependency: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/topology.py:105
msgid "No dependent supervised item"
msgstr ""

#: src/vigilo/vigiconf/loaders/topology.py:107
#, python-format
msgid "Creating dependency from %(from)s to %(to)s"
msgstr ""

